#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []

.master_based_stage: &master_based_stage
  variables:
    GIT_STRATEGY: none
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - cd /app

###########################################
###                LINT                 ###
###########################################
Lint @domifa/frontend:
  <<: *quality_stage
  <<: *master_based_stage
  allow_failure: true
  script:
    - yarn workspace @domifa/frontend lint

Lint @domifa/backend:
  <<: *quality_stage
  <<: *master_based_stage
  allow_failure: true
  script:
    - yarn workspace @domifa/backend lint

###########################################
###                TESTS                ###
###########################################
Test @domifa/backend:
  <<: *quality_stage
  stage: "Integration test"
  <<: *master_based_stage
  services:
    - name: mongo:4.0.3
  script:
    - |
      cat <<EOF > ./packages/backend/.env
      DB_USER=gitlab
      DB_PASS=test
      DB_HOST=localhost
      DB_PORT=27017
      FRONT_URL=http://localhost:4200/
      API_URL=http://localhost:3000/
      SECRET=lol
      MJ_APIKEY_PUBLIC=9b4593a46c936e6f999e1443b5526633
      MJ_APIKEY_PRIVATE=17be9fcd81da8cc6a07478c95036ec46
      ADMIN_EMAIL=domifa@yopmail.com
      EOF
    - cat ./packages/backend/.env
    - apt-get update && apt-get install -y mongodb pdftk killall
    - mongo domifa --eval "db.createUser({user:'gitlab', pwd:'test', roles:[{role:'readWrite', db:'domifa'}], passwordDigestor:'server'});"
    - mongorestore --gzip --archive=./dump_test.gzip
    - yarn workspace @domifa/backend test
    - yarn workspace @domifa/backend start:prod &
    - yarn workspace @domifa/frontend test
    - killall node
