metabase:
  enabled: true
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: metabase-pg-user
    - configMapRef:
        name: metabase-configmap

oauth2-proxy:
  host: "metabase-domifa.fabrique.social.gouv.fr"
  certSecretName: oauth2-proxy-crt
  upstream: http://metabase
  enabled: true
  envFrom:
    - secretRef:
        name: "oauth2-proxy-sealed-secret"
    - configMapRef:
        name: oauth2-proxy-configmap

app-backend:
  host: "domifa-api.fabrique.social.gouv.fr"
  replicas: 2
  certSecretName: backend-crt
  addVolumes:
    - files
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
    - secretRef:
        name: azure-domifa-volume
  env:
    - name: TZ
      value: Europe/Paris
    - name: POSTGRES_HOST
      value: "$(PGHOST)"
    - name: POSTGRES_USERNAME
      value: "$(PGUSER)"
    - name: POSTGRES_PASSWORD
      value: "$(PGPASSWORD)"
    - name: POSTGRES_DATABASE
      value: "$(PGDATABASE)"
    - name: DOMIFA_BACKEND_URL
      value: "https://domifa-api.fabrique.social.gouv.fr/"
    - name: DOMIFA_FRONTEND_URL
      value: "https://domifa.fabrique.social.gouv.fr/"
    - name: DOMIFA_PORTAIL_USAGERS_URL
      value: "https://mon-domifa.fabrique.social.gouv.fr/"
    - name: DOMIFA_PORTAIL_ADMINS_URL
      value: "https://admin-domifa.fabrique.social.gouv.fr/"
      
app-frontend:
  host: "domifa.fabrique.social.gouv.fr"
  certSecretName: frontend-crt

app-portail-admins:
  host: "admin-domifa.fabrique.social.gouv.fr"
  certSecretName: portail-admins-crt

app-portail-usagers:
  host: "mon-domifa.fabrique.social.gouv.fr"
  certSecretName: portail-usagers-crt
