projectName: domifa
dependencies:
  fabrique:
    import: socialgouv/kontinuous/plugins/fabrique
    extends:
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                pg-admin-user:
                  required: false
                azure-pg-admin-user-devflex:
                  required: false
                # secret-name:
                # enabled: true
                # reload: false
                # required: false
                # fromNamespace: <$projectName-ci>
                # toNamespace: true
                # toAllNamespace: false
                # to: azure-pg-admin-user
                # from: [azure-pg-admin-user]
